# Spam Text Classification

- N-Gram, Bi-Gram etc
- Bag of Words (BoW)
- Term Frequency Calculation TF
- Inverse Document Frequency IDF
- TFIDF Term Frequency - Inverse Document Frequency
- Text Classification

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    return text

In [ ]:
dataset = pd.read_csv('spam.tsv', sep = '\t')

In [ ]:
dataset.head()

  label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2

In [ ]:
dataset.isnull().sum()

label      0
message    0
length     0
punct      0
dtype: int64

In [ ]:
dataset.dropna(inplace=True)

In [ ]:
ham = dataset[dataset['label']=='ham']
ham.head()

  label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2
6   ham  Even my brother is not like to speak with me. ...      77      2

In [ ]:
spam = dataset[dataset['label']=='spam']
spam.head()

   label                                            message  length  punct
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
5   spam  FreeMsg Hey there darling it's been 3 week's n...     147      8
8   spam  WINNER!! As a valued network customer you have...     157      6
9   spam  Had your mobile 11 months or more? U R entitle...     154      2
11  spam  SIX chances to win CASH! From 100 to 20,000 po...     136      8

In [ ]:
ham.shape, spam.shape

((4825, 4), (747, 4))

In [ ]:
ham = ham.sample(spam.shape[0])

In [ ]:
ham.shape, spam.shape

((747, 4), (747, 4))

In [ ]:
data = pd.concat([ham, spam], ignore_index=True)

In [ ]:
data.sample(5)

    label                                            message  length  punct
289   ham                   Yar but they say got some error.      32      1
426   ham  meet you in corporation st outside gap … you c...      76      1
633   ham  Nooooooo I'm gonna be bored to death all day. ...      72      3
962  spam  SMS. ac JSco: Energy is high, but u may not kn...     154      9
718   ham  How's my loverboy doing ? What does he do that...     144      7

In [ ]:
data.shape

(1494, 4)

In [ ]:
x = data['message']
y = data['label']

In [ ]:
print(x)

0                I keep ten rs in my shelf:) buy two egg.
1          How do you guys go to see movies on your side.
2       Somebody set up a website where you can play h...
3                   Old Orchard near univ. How about you?
4                      Lol ok. I'll snatch her purse too.
                              ...
1489    Want explicit SEX in 30 secs? Ring 02073162414...
1490    ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...
1491    Had your contract mobile 11 Mnths? Latest Moto...
1492    REMINDER FROM O2: To get 2.50 pounds free call...
1493    This is the 2nd time we have tried 2 contact u...
Name: message, Length: 1494, dtype: object

In [ ]:
print(y)

0        ham
1        ham
2        ham
3        ham
4        ham
        ...
1489    spam
1490    spam
1491    spam
1492    spam
1493    spam
Name: label, Length: 1494, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
print(x_train)

932     You are a winner U have been specially selecte...
1414    Welcome to Select, an O2 service with added be...
171          Remind me how to get there and I shall do so
1047    FreeMsg: Hey - I'm Buffy. 25 and love to satis...
1296    Orange brings you ringtones from all time Char...
                              ...
1138    YOUR CHANCE TO BE ON A REALITY FANTASY SHOW ca...
204                            Oh... Kay... On sat right?
1114    sports fans - get the latest sports news str* ...
1126    How come it takes so little time for a child w...
17                            Come to me right now, Ahmad
Name: message, Length: 1195, dtype: object

In [ ]:
print(x_test)

[['no need to buy lunch for me i eat maggi mee']
 ['ok im not sure what time i finish tomorrow but i wanna spend the evening with you cos that would be vewy vewy lubly love me xxx']
 ['waiting in e car  my mum lor u leh reach home already']
 ...
 ['ambrithmaduraimet u in arun dha marrgeremembr']
 ['dear umma she called me now ']
 ['dont think so it turns off like randomlly within min of opening']]

In [ ]:
print(y_train)

[['ham']
 ['ham']
 ['ham']
 ...
 ['spam']
 ['spam']
 ['ham']]

In [ ]:
print(y_test)

[['ham']
 ['ham']
 ['ham']
 ...
 ['ham']
 ['ham']
 ['ham']]

In [ ]:
cv = CountVectorizer()
x_train_bow = cv.fit_transform(x_train.ravel())
x_test_bow = cv.transform(x_test.ravel())

/tmp/ipython-input-4250452905.py:2: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  x_train_bow = cv.fit_transform(x_train.ravel())
/tmp/ipython-input-4250452905.py:3: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  x_test_bow = cv.transform(x_test.ravel())

In [ ]:
print(x_train_bow)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 56350 stored elements and shape (4457, 7524)>
  Coords	Values
  (0, 2780)	1
  (0, 7206)	1
  (0, 7473)	1
  (0, 2695)	1
  (0, 1176)	1
  (1, 945)	1
  (1, 4816)	1
  (1, 1230)	1
  (1, 6855)	1
  (1, 4376)	1
  (1, 3066)	1
  (1, 6667)	1
  (1, 3045)	1
  (1, 6883)	1
  (1, 4572)	1
  (1, 5187)	1
  (1, 1734)	1
  (1, 1773)	1
  (1, 1772)	1
  (1, 4194)	1
  (1, 4324)	1
  (1, 6458)	1
  (1, 3199)	1
  (1, 6614)	1
  (1, 4106)	1
  :	:
  (4455, 1247)	1
  (4455, 4854)	1
  (4456, 3057)	1
  (4456, 878)	1
  (4456, 4493)	1
  (4456, 7087)	2
  (4456, 4103)	1
  (4456, 6502)	1
  (4456, 3332)	1
  (4456, 335)	1
  (4456, 397)	1
  (4456, 4298)	1
  (4456, 4464)	1
  (4456, 5702)	1
  (4456, 216)	1
  (4456, 6468)	1
  (4456, 6116)	1
  (4456, 6495)	1
  (4456, 3545)	1
  (4456, 5503)	1
  (4456, 2193)	1
  (4456, 1544)	1
  (4456, 265)	1
  (4456, 2627)	1
  (4456, 2993)	1

In [ ]:
print(x_test_bow)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13497 stored elements and shape (1115, 7524)>
  Coords	Values
  (0, 882)	1
  (0, 1885)	1
  (0, 2318)	1
  (0, 3766)	1
  (0, 3900)	1
  (0, 4249)	1
  (0, 4324)	1
  (0, 6585)	1
  (1, 561)	1
  (1, 878)	1
  (1, 1345)	1
  (1, 2037)	1
  (1, 2242)	1
  (1, 3061)	1
  (1, 3722)	1
  (1, 3900)	1
  (1, 4360)	1
  (1, 4471)	1
  (1, 6006)	1
  (1, 6258)	1
  (1, 6445)	1
  (1, 6454)	1
  (1, 6550)	1
  (1, 6619)	1
  (1, 7047)	1
  :	:
  (1111, 3025)	1
  (1111, 3676)	1
  (1111, 4805)	1
  (1111, 5733)	1
  (1111, 5931)	1
  (1111, 7467)	1
  (1112, 367)	1
  (1112, 3084)	1
  (1113, 913)	1
  (1113, 1544)	1
  (1113, 3900)	1
  (1113, 4376)	1
  (1113, 5678)	1
  (1113, 6795)	1
  (1114, 1769)	1
  (1114, 3200)	1
  (1114, 3601)	1
  (1114, 3988)	1
  (1114, 4439)	1
  (1114, 4441)	1
  (1114, 4518)	1
  (1114, 5904)	1
  (1114, 6495)	1
  (1114, 6745)	1
  (1114, 7241)	1

In [ ]:
x_train_bow.shape

(1195, 4047)

In [ ]:
tfidf = TfidfVectorizer()
x_train_tfidf = tfidf.fit_transform(x_train.ravel())
x_test_tfidf = tfidf.transform(x_test.ravel())

/tmp/ipython-input-880847442.py:2: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  x_train_tfidf = tfidf.fit_transform(x_train.ravel())
/tmp/ipython-input-880847442.py:3: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  x_test_tfidf = tfidf.transform(x_test.ravel())

In [ ]:
print(x_train_tfidf)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 56350 stored elements and shape (4457, 7524)>
  Coords	Values
  (0, 2780)	0.42866366699878194
  (0, 7206)	0.34276036166164525
  (0, 7473)	0.20908888362644776
  (0, 2695)	0.5370008822520059
  (0, 1176)	0.6055366927554009
  (1, 945)	0.11419927759266878
  (1, 4816)	0.14464833634187763
  (1, 1230)	0.12874076945960009
  (1, 6855)	0.11911090175451043
  (1, 4376)	0.1054442941790297
  (1, 3066)	0.2642322193434699
  (1, 6667)	0.2642322193434699
  (1, 3045)	0.11541079844741535
  (1, 6883)	0.2642322193434699
  (1, 4572)	0.2642322193434699
  (1, 5187)	0.2642322193434699
  (1, 1734)	0.2642322193434699
  (1, 1773)	0.2642322193434699
  (1, 1772)	0.2642322193434699
  (1, 4194)	0.2642322193434699
  (1, 4324)	0.1177457240148602
  (1, 6458)	0.2642322193434699
  (1, 3199)	0.2642322193434699
  (1, 6614)	0.2642322193434699
  (1, 4106)	0.24320278613934995
  :	:
  (4455, 1247)	0.24242752990176483
  (4455, 4854)	0.2622042269341112
  (4456, 3057)	0.15749248612596575
  (4456, 878)	0.1384948788407092
  (4456, 4493)	0.13014947891886697
  (4456, 7087)	0.2984017674857685
  (4456, 4103)	0.20194081663582433
  (4456, 6502)	0.14841644729571146
  (4456, 3332)	0.1440218958310756
  (4456, 335)	0.13409380240910415
  (4456, 397)	0.14083867524067292
  (4456, 4298)	0.18824493748736307
  (4456, 4464)	0.1909962917058144
  (4456, 5702)	0.23375488579395473
  (4456, 216)	0.16035735250696884
  (4456, 6468)	0.15951657088769988
  (4456, 6116)	0.17653403631456446
  (4456, 6495)	0.18366584324688912
  (4456, 3545)	0.2155100939375987
  (4456, 5503)	0.23680001614265017
  (4456, 2193)	0.2701061910452246
  (4456, 1544)	0.19245037263967582
  (4456, 265)	0.23231909955620003
  (4456, 2627)	0.3313353569985205
  (4456, 2993)	0.3313353569985205

In [ ]:
print(x_test_tfidf)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13497 stored elements and shape (1115, 7524)>
  Coords	Values
  (0, 882)	0.4319295993257307
  (0, 1885)	0.47798691148520833
  (0, 2318)	0.24783615789331165
  (0, 3766)	0.4668546956510182
  (0, 3900)	0.24479104100206056
  (0, 4249)	0.3539903380852067
  (0, 4324)	0.30191345065311714
  (0, 6585)	0.17089681321370018
  (1, 561)	0.17035702826791496
  (1, 878)	0.1647587179730659
  (1, 1345)	0.23731548480186515
  (1, 2037)	0.28774961923294506
  (1, 2242)	0.26729351412821883
  (1, 3061)	0.1604192663040665
  (1, 3722)	0.2018890814220516
  (1, 3900)	0.14241472670542615
  (1, 4360)	0.1660580902591164
  (1, 4471)	0.18418960654583186
  (1, 6006)	0.32132848611957615
  (1, 6258)	0.24585081171585357
  (1, 6445)	0.159777292997811
  (1, 6454)	0.12244292758412151
  (1, 6550)	0.19998985062370908
  (1, 6619)	0.23661379075778577
  (1, 7047)	0.27985867100159106
  :	:
  (1111, 3025)	0.44883892747827436
  (1111, 3676)	0.29161688798054153
  (1111, 4805)	0.326212155771744
  (1111, 5733)	0.27858160829213835
  (1111, 5931)	0.4707551076512262
  (1111, 7467)	0.326212155771744
  (1112, 367)	0.9477470275623185
  (1112, 3084)	0.3190228389109312
  (1113, 913)	0.473416763909437
  (1113, 1544)	0.38213890950728246
  (1113, 3900)	0.23770740727135473
  (1113, 4376)	0.262547324744108
  (1113, 5678)	0.39729791029562517
  (1113, 6795)	0.5886976157271855
  (1114, 1769)	0.21889842977992252
  (1114, 3200)	0.18397725814259616
  (1114, 3601)	0.23054586543069888
  (1114, 3988)	0.31530460584091546
  (1114, 4439)	0.1792742028558178
  (1114, 4441)	0.2935478070950746
  (1114, 4518)	0.4673316269038915
  (1114, 5904)	0.19367856704247
  (1114, 6495)	0.2590513071372189
  (1114, 6745)	0.4181645034019919
  (1114, 7241)	0.38662453629253374

In [ ]:
x_train_tfidf.shape

(1195, 4047)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

lr = LogisticRegression()
lr.fit(x_train_bow, y_train)
y_pred_bow = lr.predict(x_test_bow)

In [ ]:
print("Accuracy (BoW):", accuracy_score(y_test, y_pred_bow))
print(classification_report(y_test, y_pred_bow))

Accuracy (BoW): 0.9531772575250836
              precision    recall  f1-score   support

         ham       0.93      0.98      0.95       150
        spam       0.98      0.93      0.95       149

    accuracy                           0.95       299
   macro avg       0.95      0.95      0.95       299
weighted avg       0.95      0.95      0.95       299

In [ ]:
lr = LogisticRegression()
lr.fit(x_train_tfidf, y_train)
y_pred_tfidf = lr.predict(x_test_tfidf)

In [ ]:
print("Accuracy (TF-IDF):", accuracy_score(y_test, y_pred_tfidf))
print(classification_report(y_test, y_pred_tfidf))

Accuracy (TF-IDF): 0.9498327759197325
              precision    recall  f1-score   support

         ham       0.94      0.96      0.95       150
        spam       0.96      0.94      0.95       149

    accuracy                           0.95       299
   macro avg       0.95      0.95      0.95       299
weighted avg       0.95      0.95      0.95       299

In [ ]:
msg = ["Congratulations! You’ve won a free ticket!"]
msg_tfidf = tfidf.transform(msg)
print(lr.predict(msg_tfidf))

['spam']

In [ ]:
msg = ["hey, whassup"]
msg_tfidf = tfidf.transform(msg)
print(lr.predict(msg_tfidf))

['ham']

In [ ]:
msg = ["you have got free tickets to the usa this summer"]
msg_tfidf = tfidf.transform(msg)
print(lr.predict(msg_tfidf))

['spam']

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

nb = MultinomialNB()
nb.fit(x_train_bow, y_train)
y_pred_bow = nb.predict(x_test_bow)

In [ ]:
print("Accuracy (BoW):", accuracy_score(y_test, y_pred_bow))
print(classification_report(y_test, y_pred_bow))

Accuracy (BoW): 0.9531772575250836
              precision    recall  f1-score   support

         ham       0.95      0.96      0.95       150
        spam       0.96      0.95      0.95       149

    accuracy                           0.95       299
   macro avg       0.95      0.95      0.95       299
weighted avg       0.95      0.95      0.95       299

In [ ]:
nb = MultinomialNB()
nb.fit(x_train_tfidf, y_train)
y_pred_tfidf = nb.predict(x_test_tfidf)

In [ ]:
print("Accuracy (TF-IDF):", accuracy_score(y_test, y_pred_tfidf))
print(classification_report(y_test, y_pred_tfidf))

Accuracy (TF-IDF): 0.9531772575250836
              precision    recall  f1-score   support

         ham       0.95      0.95      0.95       150
        spam       0.95      0.95      0.95       149

    accuracy                           0.95       299
   macro avg       0.95      0.95      0.95       299
weighted avg       0.95      0.95      0.95       299

In [ ]:
msg = ["Congratulations! You’ve won a free ticket!"]
msg_tfidf = tfidf.transform(msg)
print(nb.predict(msg_tfidf))

['spam']

In [ ]:
msg = ["hey, whassup"]
msg_tfidf = tfidf.transform(msg)
print(nb.predict(msg_tfidf))

['ham']

In [ ]:
msg = ["you have got free tickets to the usa this summer"]
msg_tfidf = tfidf.transform(msg)
print(nb.predict(msg_tfidf))

['spam']

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

svc = SVC(C = 1000, gamma = 'auto')
svc.fit(x_train_bow, y_train)
y_pred_bow = svc.predict(x_test_bow)

In [ ]:
print("Accuracy (BoW):", accuracy_score(y_test, y_pred_bow))
print(classification_report(y_test, y_pred_bow))

Accuracy (BoW): 0.9431438127090301
              precision    recall  f1-score   support

         ham       0.93      0.96      0.94       150
        spam       0.96      0.93      0.94       149

    accuracy                           0.94       299
   macro avg       0.94      0.94      0.94       299
weighted avg       0.94      0.94      0.94       299

In [ ]:
svc = SVC(C = 1000, gamma = 'auto')
nb.fit(x_train_tfidf, y_train)
y_pred_tfidf = nb.predict(x_test_tfidf)

In [ ]:
print("Accuracy (TF-IDF):", accuracy_score(y_test, y_pred_tfidf))
print(classification_report(y_test, y_pred_tfidf))

Accuracy (TF-IDF): 0.9531772575250836
              precision    recall  f1-score   support

         ham       0.95      0.95      0.95       150
        spam       0.95      0.95      0.95       149

    accuracy                           0.95       299
   macro avg       0.95      0.95      0.95       299
weighted avg       0.95      0.95      0.95       299

In [ ]:
msg = ["Congratulations! You’ve won a free ticket!"]
msg_tfidf = tfidf.transform(msg)
print(nb.predict(msg_tfidf))

['spam']

In [ ]:
msg = ["hey, whassup"]
msg_tfidf = tfidf.transform(msg)
print(nb.predict(msg_tfidf))

['ham']

In [ ]:
msg = ["you have got free tickets to the usa this summer"]
msg_tfidf = tfidf.transform(msg)
print(nb.predict(msg_tfidf))

['spam']

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

rfc = RandomForestClassifier()
rfc.fit(x_train_bow, y_train)
y_pred_bow = rfc.predict(x_test_bow)

In [ ]:
print("Accuracy (BoW):", accuracy_score(y_test, y_pred_bow))
print(classification_report(y_test, y_pred_bow))

Accuracy (BoW): 0.9531772575250836
              precision    recall  f1-score   support

         ham       0.93      0.99      0.95       150
        spam       0.99      0.92      0.95       149

    accuracy                           0.95       299
   macro avg       0.96      0.95      0.95       299
weighted avg       0.96      0.95      0.95       299

In [ ]:
rfc = RandomForestClassifier()
rfc.fit(x_train_tfidf, y_train)
y_pred_tfidf = rfc.predict(x_test_tfidf)

In [ ]:
print("Accuracy (TF-IDF):", accuracy_score(y_test, y_pred_tfidf))
print(classification_report(y_test, y_pred_tfidf))

Accuracy (TF-IDF): 0.9498327759197325
              precision    recall  f1-score   support

         ham       0.92      0.98      0.95       150
        spam       0.98      0.92      0.95       149

    accuracy                           0.95       299
   macro avg       0.95      0.95      0.95       299
weighted avg       0.95      0.95      0.95       299

In [ ]:
msg = ["Congratulations! You’ve won a free ticket!"]
msg_tfidf = tfidf.transform(msg)
print(nb.predict(msg_tfidf))

['spam']

In [ ]:
msg = ["hey, whassup"]
msg_tfidf = tfidf.transform(msg)
print(nb.predict(msg_tfidf))

['ham']

In [ ]:
msg = ["you have got free tickets to the usa this summer"]
msg_tfidf = tfidf.transform(msg)
print(nb.predict(msg_tfidf))

['spam']